[project]
name = "mid-term-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.121.1",
    "pandas>=2.3.3",
    "scikit-learn>=1.7.2",
    "unicorn>=2.1.4",
]
